# appspec.yaml
version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        # CodeDeployがビルド成果物（artifacts）の中からtaskdef.jsonを見つけて使用します
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          # デプロイ対象のコンテナ名とポートを指定します
          ContainerName: "my-app-container" # ここはtaskdef.jsonのコンテナ名と一致させてください
          ContainerPort: 80