version: 0.2

phases:
  build:
    commands:
      - echo "{}" > taskdef.json
      - |
        cat > appspec.yaml <<EOF
        version: 0.0
        Resources:
          - TargetService:
              Type: AWS::ECS::Service
              Properties:
                TaskDefinition: <REPLACED_AT_DEPLOY>
                LoadBalancerInfo:
                  ContainerName: app
                  ContainerPort: 80
        EOF

artifacts:
  files:
    - taskdef.json
    - appspec.yaml
