version: 0.2

phases:
  build:
    commands:
      - echo Writing taskdef.json and appspec.yaml...
      - |
        cat > taskdef.json <<EOF
        {
          "family": "demo-app-green",
          "networkMode": "awsvpc",
          "containerDefinitions": [
            {
              "name": "app",
              "image": "dummy-image-uri",
              "essential": true,
              "portMappings": [
                {
                  "containerPort": 80
                }
              ]
            }
          ],
          "requiresCompatibilities": ["FARGATE"],
          "cpu": "256",
          "memory": "512",
          "executionRoleArn": "arn:aws:iam::456551560581:role/ecs-task-role"
        }
        EOF
      - |
        cat > appspec.yaml <<EOF
        version: 0.0
        Resources:
          - TargetService:
              Type: AWS::ECS::Service
              Properties:
                TaskDefinition: <REPLACED_AT_DEPLOY>
                LoadBalancerInfo:
                  ContainerName: app
                  ContainerPort: 80
        EOF

artifacts:
  files:
    - taskdef.json
    - appspec.yaml
